[display]
use_pager = true

[updates]
# Disable auto updates as it makes tealdeer chug, which defeats the purpose of
# using "a very fast implementation of tldr in Rust".
# I want it to start *instantly* every time I call it.
auto_update = false
