# Sources:
# https://youtu.be/TwxgIPAg7gc?si=C2zwvpep4kDTObcK
# https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
# https://github.com/vimichael/terminal-setup/blob/main/.tmux.conf

set -g default-shell /usr/bin/nu
set -g set-clipboard on
set -g mouse on

# Enable 256-color and true-color (24-bit) support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Start counting at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Enable vi motions
setw -g mode-keys vi

#-------------------------------------------------------------------------------
# STATUSBAR

inactive="#777777"
active="#ffffff"

set -g status-position top
set -g status-style "fg=default,bg=default"

# Window list on the left
set -g status-left ""
set -g status-justify left
set -g window-status-format "#[fg=${inactive},bold]#I:#W "
set -g window-status-current-format "#[fg=${active},bold]#I:#W "

# Session name on the right
set -g status-right "#[fg=${active},bold]#S"
set -g status-right-length 100

#-------------------------------------------------------------------------------
# BINDS

# Change prefix from Ctrl+b to Ctrl+Space
unbind C-b
set -g prefix C-Space

# Reload config with `r`
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# Split horizontally in CWD with `\`
unbind %
bind \\ split-window -h -c "#{pane_current_path}"

# Split vertically in CWD with `-`
unbind \"
bind - split-window -v -c "#{pane_current_path}"

# Create new window in CWD
bind c new-window -c "#{pane_current_path}"

# Select window with Alt+<N>
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Select prev/next window with Alt+\]
bind -n M-[ select-window -t:-1
bind -n M-] select-window -t+1

# Select pane with Alt+Arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Select pane with Alt+hjkl
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Use vim-style copy mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
