#-------------------------------------------------------------------------------
# VARIABLES

$run_menu = fuzzel

$term_class = kitty
$term = kitty
$big_term = kitty -o font_size=14

$scratch_term_class = sc-term
$scratch_term = $big_term --class $scratch_term_class

#-------------------------------------------------------------------------------
# ENVIRONMENT VARIABLES

# https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#-------------------------------------------------------------------------------
# THEMING / DARK MODE

# GTK4
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# GTK3
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
# TODO: Is this the correct name? How would I find that out?
exec = gsettings set org.gnome.desktop.interface icon-theme "adw-gtk3"

# GTK3
# env = GTK_THEME,Adwaita:dark

#-------------------------------------------------------------------------------
# MONITORS

# https://wiki.hyprland.org/Configuring/Monitors/

# name, resolution, position, scale
monitor=,preferred,auto,1.0

#-------------------------------------------------------------------------------
# WORKSPACES AND WINDOWS

# https://wiki.hyprland.org/Configuring/Workspace-Rules/
# https://wiki.hyprland.org/Configuring/Window-Rules/

# Room 1
workspace = 1, defaultName:1U, persistent:true
workspace = 2, defaultName:1I, persistent:true
workspace = 3, defaultName:1O, persistent:true

# Room 2
workspace = 4, defaultName:2U, persistent:true
workspace = 5, defaultName:2I, persistent:true
workspace = 6, defaultName:2O, persistent:true

# Room 3
workspace = 7, defaultName:3U, persistent:true
workspace = 8, defaultName:3I, persistent:true
workspace = 9, defaultName:3O, persistent:true

# Room 4
workspace = 10, defaultName:4U, persistent:true
workspace = 11, defaultName:4I, persistent:true
workspace = 12, defaultName:4O, persistent:true

# Terminal scratchpad
workspace = special:term, border:false, on-created-empty:$scratch_term
windowrule = opacity 0.7, class:$scratch_term_class
windowrule = group set always, class:$scratch_term_class

# Open new scratch terminal in scratchpad
windowrule = workspace special:term, class:$scratch_term_class

# Open browser as a group
windowrule = group set always, class:firefox
windowrule = group set always, class:Brave-browser

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Float pavucontrol
windowrule = float, class:.*pavucontrol
windowrule = size 900 700, class:.*pavucontrol
windowrule = center, class:.*pavucontrol

# Fix some dragging issues with XWayland.
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#-------------------------------------------------------------------------------
# STARTUP - INFRASTRUCTURE

# https://wiki.hyprland.org/Configuring/Keywords/

# Set wallpaper
exec-once = swaybg --image ~/walls/alena-aenami-all-i-need-1080p.jpg

# Enable top bar
exec-once = waybar

# Start notification daemon
exec-once = swaync

#-------------------------------------------------------------------------------
# STARTUP - APPLICATIONS

$room1_s1 = 1
$room1_s2 = 2
$room2 = 4
$room3 = 7
$room4 = 10

# The [workspace X] form doesn't work for some apps. Presumably X11 ones?
# You'd think Code would fully support Wayland out of the box by now, but that
# does not seem to be the case?
# TODO: Stop using Code.

# Room 1 - Library
exec-once = [workspace $room1_s1 silent] firefox
exec-once = [workspace $room1_s2 silent] qutebrowser

# Room 2 - Lab
exec-once = code
windowrule = workspace $room2 silent, class:Code

# Room 3 - Studio
exec-once = renoise
windowrule = workspace $room3 silent, class:Renoise

# Room 4 - Office
exec-once = [workspace $room4 silent] obsidian
