#-------------------------------------------------------------------------------
# PROGRAMS

$term = kitty
$scratch_term = kitty -o font_size=14 --class scratch
$run_menu = rofi -show drun
$browser = firefox
$editor = code

#-------------------------------------------------------------------------------
# ENVIRONMENT VARIABLES

# https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
