#-------------------------------------------------------------------------------
# UI

"ui.text" = "fg"
"ui.background" = { bg = "bg", fg = "fg" }
"ui.selection" = { bg = "#333333" }

# DIAGNOSTICS

error = "red"
warning = "yellow"
info = "green"
hint = "green"

"diagnostic.error" = "red"
"diagnostic.warning" = "yellow"
"diagnostic.info" = "green"
"diagnostic.hint" = "green"

#-------------------------------------------------------------------------------
# CODE

keyword = "teal"
label = "teal"
"type.builtin" = "teal"
"variable.builtin" = "teal"
"function.builtin" = "teal"
operator = "teal"

special = "dim_teal2"

punctuation = "dim_teal"

type = "green"
"type.parameter" = "green"

"constant.numeric" = "lavender"
"constant.builtin" = "lavender"

string = "purple"
"string.special.symbol" = "purple"
"constant.character" = "purple"

comment = "gray"
"comment.line.documentation" = "gray"
"comment.block.documentation" = "gray"

constant = "fg"
attribute = "fg"
variable = "fg"
namespace = "fg"
function = "fg"
tag = "fg"
constructor = "fg"
"function.macro" = "fg"

#-------------------------------------------------------------------------------
# MARKUP

"markup.heading" = { fg = "off_white", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

#-------------------------------------------------------------------------------
[palette]

bg = "#161918"
fg = "#b3b6b4"
gray = "#747877"
black = "#000000"
off_white = "#e0e0e0"

# purple = "#cd9bcd"
purple = "#c594c5"
pink = "#d88fd8 "
lavender = "#bb9af7"
teal = "#7fa396"
dim_teal = "#4a6761"
dim_teal2 = "#5a7873"
cyan = "#9eb1ff"
green = "#98c379"
orange = "#ff9e64"
# orange = "#f99157"
yellow = "#ffff57"
red = "#ee518a"
blue = "#8ca6bf"
