theme = "yo_berry"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [80]
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # Show dotfiles

[editor.lsp]
display-inlay-hints = true

[keys.normal]
"ret" = "goto_word"
C-s = ":write!"
C-x = ":write-quit-all!"
C-q = ":quit-all!"
C-g = [ ":sh ng-term" ]

[keys.insert]
C-s = ":write!"
