[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [80]
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
