theme = "yo_berry"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [80]
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # Show dotfiles

[keys.normal]
C-s = ":write!"
C-x = ":write-quit-all!"
C-q = ":quit-all!"
"ret" = "goto_word"

[keys.insert]
C-s = ":write!"
