# theme = "yo_berry"
theme = "glum"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [80]
color-modes = true
true-color = true
end-of-line-diagnostics = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # Show dotfiles

# [editor.lsp]
# display-inlay-hints = false

[keys.normal]
C-s = ":write!"
C-x = ":write-quit-all!"
C-q = ":quit-all!"
C-g = [
    ":write-all",
    ":insert-output lazygit >/dev/tty",
    ":redraw",
    ":reload-all"
]
C-r = ":config-reload"
"C-/" = ":tree-sitter-highlight-name"

[keys.insert]
C-s = ":write!"
